# All Trainer parameters available here:
# [https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html]
_target_: pytorch_lightning.Trainer   # Instantiated object
accelerator: gpu
devices: 1
min_epochs: 1                         # Force training for at least these many epochs
max_epochs: ${max_epochs}             # Stop training once this number of epochs is reached
enable_progress_bar: False            # Whether to enable or disable the progress bar