name: pytorch_tabular_autoint
_target_: src.models.tabular.pytorch_tabular.autoint.PTAutoIntModel
task: regression
loss_type: "L1Loss"
input_dim: ${in_dim}
output_dim: ${out_dim}
optimizer_lr: 0.0497648554645056
optimizer_weight_decay: 2.582935298068456e-06
scheduler_step_size: 100
scheduler_gamma: 0.8
embedding_dims: null
categorical_cardinality: null
continuous_cols: null
categorical_cols: null
attn_embed_dim: 32
num_heads: 8
num_attn_blocks: 5
attn_dropouts: 0.044129638939947105
has_residuals: false
embedding_dim: 32
embedding_dropout: 0.14340572563935186
deep_layers: true
layers: "100-50"
activation: ReLU
dropout: 0.0
use_batch_norm: false
batch_norm_continuous_input: false
attention_pooling: false
initialization: kaiming
