name: widedeep_tab_net
_target_: src.models.tabular.widedeep.tab_net.WDTabNetModel
task: regression
loss_type: "L1Loss"
input_dim: ${in_dim}
output_dim: ${out_dim}
optimizer_lr: 0.029936115638955475
optimizer_weight_decay: 3.8617741107691336e-07
scheduler_step_size: 100
scheduler_gamma: 0.8
column_idx: null
cat_embed_input: null
cat_embed_dropout: 0.1
use_cat_bias: False
cat_embed_activation: null
continuous_cols: null
cont_norm_layer: "batchnorm"
embed_continuous: False
cont_embed_dim: 16
cont_embed_dropout: 0.1
use_cont_bias: True
cont_embed_activation: null
n_steps: 5
attn_dim: 8
dropout: 0.1372998055622885
n_glu_step_dependent: 3
n_glu_shared: 4
ghost_bn: True
virtual_batch_size: 128
momentum: 0.17204050318730799
gamma: 1.210599581760608
epsilon: 1e-15
mask_type: "entmax"