# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${work_dir}/runs/${now:%Y-%m-%d_%H-%M-%S}
sweep:
  dir: ${work_dir}/multiruns/${now:%Y-%m-%d_%H-%M-%S}_${hydra.sweeper.sampler.seed}
  subdir: ${hydra.job.num}

# You can set here environment variables that are universal for all users.
# For system specific variables (like data paths) it's better to use .env file!
job:
  env_set:
    EXAMPLE_VAR: "example_value"
